// ─── Domain Components — barrel export ───────────────────────────────────────
export { CategoryForm }      from './CategoryForm'
export { Navbar }            from './Navbar'
export { ProductCard }       from './ProductCard'
export { ProductFormModal }  from './ProductFormModal'
export { ProductHistoryModal } from './ProductHistoryModal'
export { ProductDetailModal } from './ProductDetailModal'
export { AlfagiftCompare }   from './AlfagiftCompare'
export { RequireAuth }       from './RequireAuth'
export { StatCard }          from './StatCard'
export { StockBadge }        from './StockBadge'
export { ThemeSwitcher }     from './ThemeSwitcher'
